openfga/cli

README.md
Added instructions to build the CLI
- [N/A] I have added tests to validate that the change in functionality is working as expected
=> chore(docs): add build instructions to README

lib/fga/fga.go
=> feat: send a user agent in requests to fga servers

cmd/root.go
=> fix: make client creds required togther

README.md
Added documentation for getting the latest authorization model
=> chore(docs): add Read Latest Authorization Model section to the README

README.md
=> chore(docs): move Building from Source section to the top

cmd/stores/delete.go, cmd/tuples/delete.go, cmd/tuples/write.go
=> fix(write): changed output to be JSON and consistent w/ the readme

README.md
=> chore(docs): fix a few typos in the README.md

README.md
=> chore(docs): fix expand response documentation

README.md, cmd/model/model.go, cmd/query/list-relations.go, cmd/query/list-relations_test.go
=> feat(query): allow restricting relations is ListRelations

README.md, cmd/model/get.go, cmd/model/list.go, cmd/model/validate.go, cmd/model/write.go, cmd/query/expand.go, cmd/query/list-objects.go, cmd/query/list-relations.go, cmd/store/create.go, cmd/store/delete.go, cmd/store/get.go, cmd/store/list.go, cmd/tuple/changes.go, cmd/tuple/delete.go, cmd/tuple/read.go, cmd/tuple/write.go
=> chore: add command examples

cmd/model/get.go, cmd/model/list.go, cmd/query/check.go, cmd/query/list-objects.go, cmd/query/list-relations.go, cmd/store/list.go, cmd/tuple/changes.go, cmd/tuple/read.go
=> chore: make error messages more consistent

cmd/root.go
=> fix: properly exit on errors

cmd/query/list-relations.go
| Before | After |
| --- | --- |
| <img width="762" alt="Screenshot 2023-07-10 at 10 05 22 AM" src="https://github.com/openfga/cli/assets/536147/f7d9123d-2964-45f0-a6f5-c6c41677202f"> | <img width="762" alt="Screenshot 2023-07-10 at 10 05 31 AM" src="https://github.com/openfga/cli/assets/536147/bb326638-b020-4108-8afe-fe6696d048ff"> |
=> fix(query): no relations display an empty array instead of nil

.github/workflows/main.yaml, README.md, cmd/model/write.go
Write from file:
Write from args
No args or file given
- #75
=> feat(model): support writing from file via passing in the `--file` flag

.golangci.yaml, README.md, cmd/tuple/import.go, cmd/tuple/tuple.go
All Failed (1 tuple per chunk):
Some Successful, Some Failed (1 tuple per chunk):
All failed (default 20 tuples per chunk)
- #9
=> feat(tuples): support importing tuples

CHANGELOG.md
=> release(v0.1.0-beta): update changelog

.goreleaser.yaml
=> fix(ci): fix go releaser config

.goreleaser.Dockerfile, .goreleaser.yaml
Source: https://www.goreleaser.com/errors/docker-build/
- closes #80
=> fix(ci): fix building docker image

CHANGELOG.md
=> release(v0.1.0-beta1): update changelog

.github/dependabot.yaml
Group dependabot updates and make them weekly
- [Dependabot Docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)
=> chore: update dependabot config

cmd/model/get.go, cmd/model/list.go, cmd/model/model.go, cmd/model/validate.go, cmd/model/write.go, cmd/query/check.go, cmd/query/list-objects.go, cmd/query/list-relations.go, cmd/query/query.go, cmd/store/create.go, cmd/store/delete.go, cmd/store/get.go, cmd/store/list.go, cmd/store/store.go, cmd/tuple/changes.go, cmd/tuple/delete.go, cmd/tuple/import.go, cmd/tuple/read.go, cmd/tuple/tuple.go, cmd/tuple/write.go
=> chore: make descriptions more consistent

README.md
=> chore(docs): add installation instructions

CHANGELOG.md
=> release(v0.1.0-beta2): update changelog

.github/workflows/main.yaml
=> chore(ci): require shellcheck to pass for release

internal/build/build.go, internal/fga/fga.go
=> fix: build information is now overridable at build time

.golangci.yaml, cmd/model/get.go, cmd/model/list.go, cmd/model/model.go, cmd/model/transform.go, cmd/model/validate.go, cmd/model/validate_test.go, cmd/model/write.go, cmd/model/write_test.go, cmd/store/create.go, go.mod, go.sum, internal/authorizationmodel/authorizationmodel.go, internal/authorizationmodel/format.go, internal/authorizationmodel/model.go, internal/authorizationmodel/model_test.go, internal/authorizationmodel/read-input-or-arg.go, internal/slices/contains.go, internal/slices/slices.go
=> feat(model): add transform command & support fga dsl output

cmd/model/transform.go
Fixes https://github.com/openfga/cli/issues/109
Fixes the `fga model transform` help content
Fixes https://github.com/openfga/cli/issues/109
=> fix: fixed transform output and help

README.md
Update readme with updates to `fga store create` `fga model write` `fga model get` `fga model list`.
Also updated default value for `fga tuple import``--max-tuples-per-write parameter
=> chore: update readme with iteration 2 features

README.md, cmd/model/validate.go, cmd/store/create.go
- Updated help for `fga model validate`
- Updated help for `fga store create`
- Added `fga model transform` docs
- Closes https://github.com/openfga/cli/issues/108
- Closes https://github.com/openfga/cli/issues/112
- [] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
=> fix: updated readme and command docs

cmd/tuple/import.go, cmd/tuple/tuple.go, cmd/tuple/write.go
=> fix(tuple): model id is only accepted on import and write

.github/workflows/main.yaml, go.mod, go.sum
=> chore(deps): upgrade dependencies

CHANGELOG.md
=> release: v0.1.0-beta5

CHANGELOG.md
=> release: v0.1.0-beta6

CHANGELOG.md
=> release(v0.1.0): with model dsl parsing fixes

cmd/model/test.go, internal/storetest/testresult.go, internal/storetest/tests.go
=> fix(model): exit with error when any model test fails

README.md
Added instructions on how to delete all tuples in a store
=> chore: instructions to delete all tuples in a store

README.md
Fixes https://github.com/openfga/cli/issues/171
=> chore:update example for yaml tests

CHANGELOG.md
=> release(v0.1.2): imporvements to read and write

CHANGELOG.md
=> chore: fix changelog for v0.1.2 release

.github/workflows/main.yaml, .golangci.yaml, Makefile
This PR brings some improvements to the Makefile. More info within the comments below. ⬇️
=> chore: bring improvements to the makefile

CHANGELOG.md
Pending open PRs to be included in this release:
=> release(v0.2.2): with store import and better condition support

CHANGELOG.md
=> release(v0.2.3): support importing tuples from csv files

CHANGELOG.md, internal/storetest/read-from-input.go
=> fix: reading json models & release v0.2.4

Makefile
=> chore: fix build step in makefile

cmd/model/write_test.go, cmd/store/import.go, cmd/tuple/write.go, cmd/tuple/write_test.go, internal/storetest/read-from-input.go, internal/storetest/storedata.go, internal/tuplefile/csv.go, internal/tuplefile/read.go
=> feat: support referencing csv file in fga store file

CHANGELOG.md, README.md
=> release: v0.2.7

CHANGELOG.md
=> release: v0.3.0-beta.1

.github/workflows/main.yaml, .github/workflows/semgrep.yaml, CHANGELOG.md, README.md
Merges the main branch into modular models to resolve conflicts before merging modular models to main
=> Merge main into modular models branch

CHANGELOG.md
=> release: v0.3.0

README.md
=> chore(docs): update read documentation in readme

cmd/tuple/import.go
I have added the function `extractErrorMssg` to extract out the relevant part of the errror message in the `reason` field.
Fixes #255
=> feat: simplify error messages on tuple write

README.md
Added missing content for the Store Export command, in the table of contents as well as the Store command options.
=> docs: additional store export docs

cmd/store/import.go
Used file name as default store name
Fixes #316
=> Used file name as default store name

cmd/store/import.go
When we're performing an import to an existing store, first perform a lookup of the store so that we can:
* Error if this store does not exist
* OpenFGA will not error if provided a store ID on model write that doesn't exist (https://github.com/openfga/openfga/issues/690), so we can force this into an error by attempting to lookup the store first and bubbling up the error
* Retrieve the store metadata to allow us to output the store/model information
Also refactors the code a little to remove some of the unnecessary `nolint` directives
Closes #334
=> fix(import): output store and model information when including a store id

cmd/store/import.go
=> fix: handle get store errors on store import

CHANGELOG.md
=> release: v0.6.0

README.md
Changed issuer for Okta FGA example
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)
=> chore(docs): update example for Okta FGA to account for changed issuer

README.md
Okta FGA has re-branded to Auth0 FGA
=> fix: readme doc
