cmd/models/list.go
cmd/models/list_test.go
cmd/stores/list.go
cmd/tuples/changes.go
cmd/tuples/read.go

Correct possible infinite loop as continuation token not used correctly.
Close https://github.com/openfga/cli/issues/28

fix: correct infinite loop for continuation token

---

cmd/models/list.go
cmd/models/list_test.go
cmd/stores/list.go
cmd/stores/list_test.go
cmd/tuples/read.go
cmd/tuples/read_test.go

Fix the infinite loop problem when continuation token is empty
follow up of https://github.com/openfga/cli/pull/29

fix: empty coninuation token means last page

---

README.md

- Changed the model we use for `models write` so it has the relation that we then use in the rest of the examples
- Fixed examples where the results were not consistent with the model/tuples provided
- Fixed the `tuples changes` example so it returns what it's actually returning ig
- Removed duplicated license entry

chore: updates in model examples and other fixes

---

go.mod
go.sum

Fix issue where CLI fails when auth model id not provided
Close https://github.com/openfga/cli/issues/47

chore: bump go-sdk version

---

cmd/query/expand.go

Fix expand to use correct number of parameter
Close https://github.com/openfga/cli/issues/51
Run `./fga query expand --store-id="01H4PBMQC927DTAWD8P64CVA4W" owner doc:roadmap` and see the correct result

fix: expand to expect correct number of parameter

---

.golangci.yaml
README.md
cmd/root.go
lib/cmd-utils/bind-viper-to-flags.go

I'm leaving the config file bit undocumented for now, but if anyone wants to try it, you can place `.fga.yaml` in your home directory or in your user config directory or under the `fga` folder of your config directory.
The contents of the file are of this format:
```yaml
server-url: http://localhost:8080
store-id: 01FQH7RTCYK15CAJS9FQGMCKPY
model-id: 01GVKXGDCV2SMG6TRE9NMBQ2VG
```
closes #12
closes #37

feat: load flags from  env & config file

---

cmd/query/list-relations.go
cmd/query/list-relations_test.go

If model reports there is no relations, we should short-circuit and returns empty relations.
Close https://github.com/openfga/cli/issues/61
Based on https://github.com/openfga/cli/issues/61, output will be
```
./fga query list-relations --store-id 01H4S674PM9E2Z10YAPQZ15XFF doc:xxx user:xxx
{
"relations": []
}
```

fix: correct behaviour if model has empty relations

---

cmd/root.go
cmd/version.go
internal/build/build.go

Adds the `fga version` command to the CLI.
#70

feat: add `fga version` command to the CLI

---

go.mod
go.sum

chore of bumping openfga go-sdk version to fix issues associated with not respecting options and body

chore: bumping openfga go-sdk version

---

.goreleaser.yaml
cmd/version.go
internal/build/build.go
lib/fga/fga.go

makes the user agent consistent with the SDKs

fix: drop the `v` prefix for versioning

---

.goreleaser.yaml

Adds a Homebrew tap release process to the goreleaser manifest.
https://github.com/openfga/cli/issues/57

ci: add homebrew-tap release process to goreleaser manifest

---

cmd/tuple/import.go

- we are now defaulting to 1 for usuability (previously reimporting would fail for some new tuples because other tuples have already been imported)
- to work around the slower import, max parallel writes have been increased to 10
- closes #103

fix(tuple): change default max tuples per write in import

---

.goreleaser.yaml

Drops the create PR feature for the homebrew-tap release process. This is what goreleaser does in their releases anyways..
https://github.com/goreleaser/goreleaser/blob/main/.goreleaser.yaml#L172-L194

ci(goreleaser): drop pull request in goreleaser homebrew-tap

---

internal/fga/fga.go

This fixes `tuple import` without a specified Model ID.
https://github.com/openfga/cli/pull/124
https://github.com/openfga/go-sdk/blob/f6922b2d8c6d9dc5532bd0cec67c55aac1924ff7/client/client.go#L432-L443 (should likely fix this condition in the sdk as well)

fix: set model id as nil if empty

---

README.md

Fixed examples where we mentioned you had to write `--file:filename` instead of `--file filename`

chore: fixed --file examples

---

README.md

Tweaked the readme section about OAuth authentication so the settings work for Auth0 FGA

chore: add example that works for Auth0 FGA

---

README.md
cmd/model/model.go
cmd/model/test.go
example/model.fga
example/tests.fga.yaml
internal/authorizationmodel/read-from-input.go
internal/authorizationmodel/tests.go

To test:
- `make build`
- `./dist/fga model test --file example/model.fga --tests example/tests.fga.yaml` to write and test a model
- `./dist/fga model test  --tests example/tests.fga.yaml` to test a previously written model
- `./dist/fga model test  --tests example/tests.fga.yaml --verbose` to see the full JSON output
Closes #136

feat(model): add test command

---

README.md
cmd/root.go
internal/cmdutils/get-client-config.go
internal/fga/fga.go

`server-url` is still read if `api-url` is not provided for backward compatibility

fix(config): use api-url instead of server-url to maintain consistency w/ sdks

---

internal/authorizationmodel/read-from-input.go
internal/clierrors/clierrors.go

We still print out the help message so users can know what input we expect, but we also return an error and block the processing.
- Closes #145

fix: throw error when model input missing

---

README.md

- added instructions to convert `tuple read` to `tuple import` syntax
- fixed a broken link

chore: added instructions to convert `tuple read` to `tuple import` 

---

.github/workflows/main.yaml

chore(ci): only run push workflow on main and on tags

---

CHANGELOG.md

release(v0.1.1): `fga model test` now exits with error on test failure

---

README.md
cmd/tuple/read.go
cmd/tuple/read_test.go

aims to close #111 
I made the read function to return a "complete" version and a "simple" version of the JSON that can be imported by `tuple write` and `tuple delete` with the flag `--file`.
now if its informed the `--simple-json` flag the response is this:
```
./dist/fga tuple read --store-id 01HB3AZ6RAAGHJQ9HKXV9C89SE --simple-json
[
{
"object":"document:Z",
"relation":"reader",
"user":"user:gabriel"
},
{
"object":"document:Z",
"relation":"reader",
"user":"user:anne"
},
{
"object":"document:Z",
"relation":"reader",
"user":"user:jones"
}
]
```
without the flag:
```
./dist/fga tuple read --store-id 01HB3AZ6RAAGHJQ9HKXV9C89SE              
{
"tuples": [
{
"key": {
"object":"document:Z",
"relation":"reader",
"user":"user:gabriel"
},
"timestamp":"2023-09-27T10:58:46.209655Z"
},
{
"key": { …
```

feat: create the --simple-json flag for tuple read

---

README.md
cmd/tuple/read.go
cmd/tuple/write.go

fix: in read, rename `--simple-json` to `--simple-output`

---

.golangci.yaml
cmd/model/validate.go
cmd/tuple/import.go
internal/storetest/localtest.go
internal/storetest/remotetest.go
internal/storetest/storedata.go
internal/storetest/testresult.go

- fix: prevent panic when no context is present
- chore: make `make lint` happy
https://github.com/openfga/cli/pull/169

fix: prevent panic when no context is present

---

README.md
example/folder-document-access_tuples.json
example/model.fga.yaml
example/model_tuples.yaml
internal/storetest/localstore.go
internal/storetest/storedata.go
internal/storetest/tests.go

Adds support for using `tuple_file` instead of `tuples` in a test file. The file can be either a `yaml` or `json` syntax. All tuple files are loaded upfront before running tests so that we can ensure that the test run will be functional and all errors are collated and presented to the user like below.
```
fga model test --tests ./example/model.fga.yaml
Error: error running tests due to failed to process one or more tuple files
failed to process global tuple ./model_tuples.yaml file due to yaml: line 7: could not find expected ':'
failed to process tuple file ./folder-document-access_tuple.json for test folder-document-access due to open example/folder-document-access_tuple.json: no such file or directory
exit status 1
```
The `model.fga.yaml` example has been updated to show this and also …

feat(test): support referenvcing a tuple_file instead of tuples

---

README.md
cmd/tuple/changes.go
cmd/tuple/changes_test.go

This PR adds a `--continuation-token` flag to the `fga tuple changes` command to allow passing a continuation token that was provided by the FGA server. It also now logs the last retrieved continuation token alongside the changes output
<details>
<summary>Sample output</summary>
```
fga tuple changes --store-id 01HKMFHMD00Z298PFBT848K1N0
{
"changes": [
{
"operation":"TUPLE_OPERATION_WRITE",
"timestamp":"2024-01-08T12:08:01.312914916Z",
"tuple_key": {
"object":"group:foo",
"relation":"member",
"user":"user:anne"
}
},
{
"operation":"TUPLE_OPERATION_DELETE",
"timestamp":"2024-01-08T12:10:21.524092718Z",
"tuple_key": {
"object":"group:foo",
"relation":"member",
"user":"user:anne"
}
},
{
"operation":"TUPLE_OPERATION_WRITE",
"timestamp":"2024-01-08T12:10:29.012827054Z",
"tuple_key": { …
```

feat(changes): accept continuation token as a command line argument, display last token

---

README.md

Docs change for installing OpenFGA cli on Windows via Scoop. 
Scoop manifest was added via: https://github.com/ScoopInstaller/Main/pull/5331
Requested by @aaguiarz : https://github.com/ScoopInstaller/Main/issues/5330#issuecomment-1890778934

docs: add scoop install via windows

---

.gitignore
README.md
cmd/root.go
internal/cmdutils/get-client-config.go
internal/fga/fga.go

Fully support OAuth2.
Add oauth2 scopes support, also update go-sdk to support full token endpoint url as issuer (and not only the host name).
blocked by #235 
closes #231

feat: oauth2 support

---

.goreleaser.yaml

This PR updates the goreleaser configuration to create per-release brew formulae. This allows developers to install specific versions of the CLI:
```
brew install openfga/tap/fga@<version>
```
```
brew tap openfga/tap
brew install fga@<version>
```
Closes #95.
Implemented based on [guidance from goreleaser](https://www.github.com/goreleaser/goreleaser/issues/4204).

ci(goreleaser): create per-release brew formulae

---

internal/storetest/localstore.go
internal/storetest/tests.go

This is a follow-up of https://github.com/openfga/openfga/pull/1318.
This PR cleans server resources properly.

chore: cleanup FGA server resources

---

cmd/man.go
cmd/model/get.go
cmd/model/list.go
cmd/model/test.go
cmd/model/validate_test.go
cmd/store/create.go
cmd/store/delete.go
cmd/store/get.go
cmd/store/import.go
cmd/store/list.go
cmd/tuple/changes.go
cmd/tuple/import.go
cmd/tuple/read.go
cmd/tuple/write.go
cmd/version.go
internal/cmdutils/get-contextual-tuples_test.go
internal/confirmation/confirmation_test.go
internal/storetest/testresult.go

Simplify test output as outlined in https://github.com/openfga/cli/issues/251
Closes https://github.com/openfga/cli/issues/251
I would be happy to change the output/code to suit what you prefer.
```
$ ./dist/fga model test --tests tests.fga.yaml
(FAILING) test-1: Checks (2/3 passing) | ListObjects (2/2 passing)
ⅹ Check(user=user:anne,relation=can_share,object=folder:1, context=<nil>): expected=false, got=true, error=<nil>
---
(FAILING) test-1b: Checks (2/3 passing) | ListObjects (1/2 passing)
ⅹ Check(user=user:anne,relation=can_share,object=folder:1, context=<nil>): expected=false, got=true, error=<nil>
ⅹ ListObjects(user=user:anne,relation=can_view,type=folder, context=<nil>): expected=[folder:2], got=[folder:1 folder:2], error=<nil>
---
Tests 2/4 passing
Checks 5/7 passing
ListObjects …
```

chore: simplify test output

---

go.mod
go.sum

The Go SDK fixed the marshalling issue that was escaping HTML characters, so lets update to latest
Closes #188

fix: update go sdk to no escape characters

---

README.md
internal/storetest/testresult.go

Test results displayed information that was not necessarily relevant:
- When the number of tests run for a specific method (check/listobjects) was 0, it displayed 0 instead of not showing anything
- When no `context` was provided, it showed `context =<nil>` instead of  not showing it
- When no `error` was returned, it showed `error =<nil>` instead of  not showing it
- When no tests failed, it showed two new lines and a separator, before showing the summary, when it was not needed
This PR addresses this by not showing unnecessary data.
I tested manually:
- If an error is returned, it should be displayed
- If context is provided, it should be displayed
- If there aren't any Check or LIstObjects tests, the tests result should not mention those

chore: simplify testing results output

---

cmd/store/create.go
cmd/store/import.go
internal/storetest/localstore.go

Adds support for handling `model_file` in a store file pointing at an `fga.mod` file, this completes with support for both the `model test` and `store import` command.
In order to test the `import` command you'll need [this branch](https://github.com/openfga/openfga/tree/feat/1402-schema-12-support) of openfga checked out and started with `openfga run --experimentals=enable-modular-models`, that will then allow importing by referencing the `fga.mod` file in the modular-models-example repo
Closes #269

feat: support referencing an fga.mod file in a store

---

.github/CODEOWNERS

Based on https://github.com/openfga/sdk-generator/pull/322 I think the intention is for readme changes approvers to be community, product and DX but I guess GH codeowners doesn't apply DX to the readme from the * rule

chore: allow dx to approve readme changes

---

cmd/store/import.go

importStore function in `/cmd/store/import.go` now also returns the response details after creating store with model which is used in importCmd to display those details
Fixes #298

feat: fga store import displays the generated store and model details

---

README.md
cmd/model/write.go
internal/authorizationmodel/format.go

Adds a modular write example to the readme and fixes the JSON write example in the command help text
Closes #291

doc(model/write): add missing example to readme, correct help text example

---

README.md
cmd/model/get.go
cmd/model/get_test.go
cmd/store/export.go
cmd/store/export_test.go
cmd/store/store.go
cmd/tuple/read.go
cmd/tuple/read_test.go
internal/authorizationmodel/read-from-store.go
internal/storetest/storedata.go
internal/tuple/read.go

Adds a new command to export a store to YAML, either to a file on disk or to STDOUT. The command can write either to STDOUT, or to a file depending on whether the `output-file` flag is specified. If writing to a file, and the file already exists, the user will be prompted to overwrite.
Example help:
```
fga store export --help
Export a store to YAML
Usage:
fga store export [flags]
Examples:
fga store export
Flags:
-h, --help                 help for export
--model-id string      Authorization Model ID
--output-file string   name of the file to export the store to
--store-id string      store ID
```
Example output:
```
fga store export --model-id 01HSX7MS9Y4K5M50HBA3HVA07X
name: Test
model: |+
model
schema 1.1
type user
type group
relations
define member: [user]
define moderator: [user] …
```

feat: add export store command

---

README.md
cmd/model/transform.go

Adds support for a `--output-format` option that allows specifying `fga` or `json` for the transform output, this is optional and will continue to support outputting `fga` for `json` input and `json` for `fga` and `modular` inputs.
It doesn't prevent transforming to the same as the input as while not useful, it will work so shouldn't be an error case.
Closes #307

feat(model/transform): support specifying an output format

---

README.md
cmd/query/list-users.go
cmd/query/list-users_test.go
cmd/query/query.go
go.mod
go.sum
internal/mocks/client.go

Adds support for `fga query list-users` which will call the [ListUsers](https://github.com/openfga/rfcs/blob/main/20231214-listUsers-api.md) API and return the list of users and excluded users for the stated object and relation.
There's a demo below and the command is as follows
```
fga query list-users --store-id 01HWQ7ARKQ2SWXK35R2HADMDH0 --object document:1 --relation viewer --user-filter user --contextual-tuple "user:bob member group:fga-core"
fga query list-users --store-id 01HWQ7ARKQ2SWXK35R2HADMDH0 --object document:1 --relation viewer --user-filter group#member --contextual-tuple "group:fga-int#member member group:fga"
fga query list-users --store-id 01HWQ7ARKQ2SWXK35R2HADMDH0 --object document:1 --relation viewer --user-filter user --contextual-tuple "group:fga-int#member member …
```

feat(query): support running a query against list-users api

---

.golangci.yaml
cmd/model/validate.go
cmd/query/check.go
cmd/query/expand.go
cmd/query/list-objects.go
cmd/query/list-relations.go
cmd/store/export.go
cmd/tuple/delete.go
internal/authorizationmodel/model.go
internal/cmdutils/get-contextual-tuples.go

Latest version of golangci deprecated the `gomnd` linter and replaced it with `mnd`, so disable `gomnd` (as it's still in the default set) and replace with `mnd`
https://github.com/openfga/cli/actions/runs/8969453051/job/24630885443?pr=322

build: replace gomnd with mnd

---

.github/workflows/main.yaml

Adds generation of slsa provenance during release, this is pretty much just the usage in the openfga repo with some very minor changes to use `openfga/cli` and `fga` instead of `openfga/openfga/` and `openfga` for image and binary names,
[openfga/openfga usage](https://github.com/openfga/openfga/blob/f8505ce62c4cc0c882755e7bf21e3f8e0c8278d5/.github/workflows/release.yaml#L68-L198)

ci: generate slsa provenance

---

CHANGELOG.md

```
Added:
- Support asserting the `excluded_users` in `list_users` tests (#337)
Fixed:
- `fga store import` now outputs store and model details when writing to an existing store (#336)
```

release: v0.4.1

---

.github/workflows/main.yaml
.goreleaser.yaml

The deprecations we had were the [brew.folder](https://goreleaser.com/deprecations/#brewsfolder) property, renamed to directory and the [usage of --skip-<value> flags](https://goreleaser.com/deprecations/#-skip) which are replaced by a single --skip flag that accepts the values to skip

ci: move to using goreleaser v2

---

README.md
example/model.fga.yaml
go.mod
go.sum
internal/storetest/conversion.go
internal/storetest/conversion_test.go
internal/storetest/localtest.go
internal/storetest/remotetest.go
internal/storetest/storedata.go
internal/storetest/testresult.go

Removes `excluded_users` from ListUsers response as it was removed from OpenFGA with https://github.com/openfga/api/pull/171 and https://github.com/openfga/sdk-generator/pull/377.
This feature was originally a well-intentioned way to communicate any negations that may exist on public-typed wildcard (e.g. user:*) as a means of being abundantly clear about what a user:* result entails. However, as we discover more possible situations where excluded users could arise, we realize that we were making a premature decision about the API. We fully intend to re-add excluded_users at some point in the future but may or may not be a flattened list as previously implemented.
This was tested with a locally-generated version of the Go SDK.
**Please note:** 
- This is a draft until the Go SDK is rebuilt …

Removing excluded users from ListUsers response

---

.golangci.yaml
cmd/store/import.go
go.mod
go.sum

This pull request adds a progress bar to the store import feature. Previously, the import process did not provide any visual feedback to the user, making it difficult to determine the progress. With this change, a progress bar is displayed, indicating the number of tuples being imported. This improves the user experience and provides better visibility into the import process.
See video below in slow-mode _(or test with super long file)_ :
https://github.com/openfga/cli/assets/55068936/adb5790c-16f3-4001-bf28-b971b6f0185e
- Open this PR in Gitpod (it would automatically run the required commands to install deps.) or in local.
- Add a `demo.fga.yaml` file under `cmd/fga`
- Under `cmd/fga` directory run the following command:
```sh
go run main.go store import --file …
```

feat(import): add progress bar for store import

---

cmd/store/import.go

fix: breaking change output of store import cmd

---

.github/workflows/main.yaml
.gitignore
Makefile
tests/scripts/run-test-suites.sh
tests/store-test-cases.yaml

This PR adds support for testing the CLI commands through the use of the [commander tool](https://github.com/commander-cli/commander), and thus having complete E2E tests. Furthermore we are able to also calculate coverage support through the latest Go tool chain improvements.
In order to run the tests, we are using a locally running openfga server that gets spinned up through docker.

test: add commander testing infrastucture

---

cmd/model/validate.go
cmd/store/import.go
cmd/tuple/delete.go
cmd/tuple/import.go
cmd/tuple/write.go
internal/authorizationmodel/model.go
internal/authorizationmodel/model_test.go

New version of golangci-lint, new failures. Rather than silence them I tried to approach solving them properly by making use of `ulid.Time` or correctly typing things.
See failures [here](https://github.com/openfga/cli/actions/runs/10631105558/job/29471326424?pr=381)

refactor: fix lint warnings

---

internal/authorizationmodel/format.go

Changes the default format to `autodetect` to better describe the default behaviour
<details>
<summary>fga model transform help text</summary>
```
Flags:
--file fga.mod           File Name. The file should have the model in the JSON or DSL format or be an fga.mod format
-h, --help                   help for transform
--input-format format    Authorization model input format. Can be "fga", "json", or "modular" (default autodetect)
--output-format format   Authorization model output format. Can be "fga" or "json"." (default autodetect)	
```
</details>

refactor: change default name for model format to improve help text

---

README.md
cmd/query/check.go
cmd/query/check_test.go
cmd/query/expand.go
cmd/query/expand_test.go
cmd/query/list-objects.go
cmd/query/list-objects_test.go
cmd/query/list-relations.go
cmd/query/list-relations_test.go
cmd/query/list-users.go
cmd/query/list-users_test.go
cmd/query/query.go
cmd/store/export.go
cmd/store/export_test.go
cmd/tuple/read.go
cmd/tuple/read_test.go
internal/cmdutils/get-consistency.go
internal/cmdutils/get-consistency_test.go
internal/tuple/read.go

Adds support for the `--consistency` parameter to the query commands to allow usage of that feature.
For more details see the [relevant openfga/openfga PR](https://github.com/openfga/openfga/pull/1764).
Closes #379

feat: support usage of consistency parameter

---

cmd/store/import.go
cmd/tuple/delete.go
cmd/tuple/import.go
cmd/tuple/write.go

Overlooked the need to change the flag declaration as part of the refactoring here #382.
Will work on adding some integration tests to cover this.
Fixes #387

fix: correct flag value type in delete, import, and write

---

.gitignore
tests/fixtures/basic-model.fga
tests/fixtures/basic-store.fga.yaml
tests/fixtures/basic-tuples.json
tests/import-tests-cases.yaml
tests/scripts/run-test-suites.sh
tests/scripts/test-data/get-model-id.sh
tests/scripts/test-data/get-store-id.sh
tests/tuple-test-cases.yaml

Adds tests that cover the failure cases from #387
This is the first example of how we can potentially create and reuse stores and models between tests based on the learnings from Auth0 CLI testing. Although we might not need that, being able to reuse between tests might shave off a small amount of time.
These will fail until #389 is merged

test: add integration tests for store import and tuple write/delete

---

CHANGELOG.md

```
Fixed:
- Fixed issue where `fga store import`, `fga tuple write` and `fga tuple delete` could not be ran due to an issue with the `--max-tuples-per-write` and `--max-parallel-requests` options (#389)
- Fixed an issue where List Users failed test output did not include the returned response (#391)
```

release: v0.6.1

---

cmd/model/list.go
cmd/query/check.go

This pull request updates the error messages in the check function to provide more informative and concise error messages. The "failed to check" error message has been changed to "check failed" to better reflect the actual error.
Updated error message would look like:
> Error: check failed: <error_message>
Actual Example: 
> Error: check failed: Post "http://localhost:8080/stores/01H4P8Z95KTXXEP6Z03T75Q984/check": dial tcp [::1]:8080: connect: connection refused
fixes #404
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)

simplify err messages in check function

---

cmd/model/list.go
cmd/store/import.go

Fixes #368
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)

fix: don't attempt to import tuples if none are present

---

cmd/root.go

Given that it is deprecated, hide the `--server-url` flag from the help output. I did not change to use `MarkDeprecated` because we're already logging ourselves [here](https://github.com/openfga/cli/blob/main/internal/cmdutils/get-client-config.go#L32-L36)
If you haven't done so yet, we would appreciate it if you could star the [OpenFGA repository](https://github.com/openfga/openfga). :)

chore: hide server-url flag from help output

---

go.mod
go.sum
internal/mocks/client.go

Points `openfga/go-sdk` to the main branch and regenerates the mock to include the getter/setters for Store ID and Model ID

chore(deps): update go-sdk and generate mock based on new interface

---

cmd/store/create.go
cmd/store/import.go
cmd/store/import_test.go

When importing a store, we usually import the model and the tuples from the file. But these changes enable us to also import the assertions (only Check assertions) from the Model Tests as a part of the store import.
closes https://github.com/openfga/cli/issues/224

feat: support importing assertions as part of a store

---

CHANGELOG.md

```
- Support for start-time parameter in changes command (#443)
- Support importing assertions during `fga store import` (#446) - Thanks @sujitha-av
```

release: v0.6.4

---

README.md

This PR replaces instances of `tuple import` (deprecated) by `tuple write` and avoid getting the warning when following the README instructions 
```
Command "import" is deprecated, use the write/delete command with the flag --file instead
```

chore: Update README.md to replace import by write command when importing tuples

---

.github/workflows/main.yaml
.golangci.yaml
cmd/model/transform.go
cmd/store/create.go
cmd/tuple/delete.go
cmd/tuple/write.go
internal/authorizationmodel/read-from-input.go
internal/storetest/storedata.go
internal/tuple/import.go
internal/tuplefile/csv.go
internal/tuplefile/read.go

This PR migrates the project to golangci-lint v2 to support golangci/golangci-lint-action v7.
Changes:
- Added version field to .golangci.yaml
- Updated linter configuration syntax
- Updated nolint directives to use new linter names
The migration was done following the official migration guide: https://golangci-lint.run/product/migration-guide/
Fixes https://github.com/openfga/cli/pull/474#issuecomment-2768769262

chore: migrate to golangci-lint v2

---

cmd/model/validate.go
internal/authorizationmodel/model.go
internal/fga/fga.go

This PR fixes the `fga model validate` command to properly exit with a non-zero status code when validation fails, making it more useful in CI/CD pipelines and build tools like Bazel.
Also fixed some linting issues related to function ordering in the codebase.
fixes #484

fix: validate command to exit with non-zero status on errors

---

CHANGELOG.md

Added:
- Allow to use `tuples` and `tuple_file` together in the store file (#369) - thanks @DanielBertocci
- Add `--suppress-summary` flag to `model test` command (#407) - thanks @Siddhant-K-code
Changed:
- fix validate command to properly exit with non-zero status on errors (#485) - thanks @Siddhant-K-code

release: v0.6.6

---

README.md

Solves 
#502 
This can avoid the confusion if someone is referring to the readme for the CLI commands

fix: readme change for removing --model-id from tuple read cmd
